### ISSUE TITLE
Transformer structs.jsonpath fails when selector is $

### ISSUE THREAD

**Issue by Wholteza** [Hoglandets-IT/beetl#19]
## Reproduction steps:
```yaml
...
sourceTransformers:
  - transformer: structs.jsonpath
    config:
      inField: anyField
      outField: anyField
      jsonPath: $
```

## Expected result
$ is referring to the root object, so if it's the only selector the transformer should select the inField value.
